# Generated by Django 5.1 on 2024-09-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_juego_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
            preserve_default=False,
        ),
    ]
