# Generated by Django 5.1 on 2024-10-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_juego_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='imagen',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/'),
        ),
    ]
